### ISSUE TITLE
Add cluster-api-provider-vcluster information to CAPI docs quickstart

### ISSUE THREAD

**Issue by matskiv** [loft-sh/cluster-api-provider-vcluster#12]
As suggested in #11 - vcluster isn't added to the https://cluster-api.sigs.k8s.io/user/quick-start.html
We should add the basic variables and cluster creation command there.

**Comment by oscr** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/7004

**Comment by matskiv** [comment]
This is great. Thank you @oscr :+1: :raised_hands:
