### ISSUE TITLE
pods stuck in pending

### ISSUE THREAD

**Issue by stefanpinterBE** [loft-sh/cluster-api-provider-vcluster#19]
Hi!

i tried to set a vcluster up with the instructions at [https://www.vcluster.com/docs/operator/cluster-api-provider](https://www.vcluster.com/docs/operator/cluster-api-provider)

now  0/2 pods are up with the following warnings, it didn't instruct me to add persistensvolumes anywhere though.

```
  Warning  FailedScheduling  6m5s                   default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  3m48s (x1 over 4m48s)  default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
```

my variables:

```
export KUBERNETES_VERSION="1.23.15"
export HELM_VALUES=""

export CLUSTER_NAME=testvcluster
export CLUSTER_NAMESPACE=testvcluster
```

```
NAME                 READY   STATUS    RESTARTS   AGE
pod/testvcluster-0   0/2     Pending   0          10m

NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/testvcluster            ClusterIP   10.104.49.84   <none>        443/TCP   10m
service/testvcluster-headless   ClusterIP   None           <none>        443/TCP   10m

NAME                            READY   AGE
statefulset.apps/testvcluster   0/1     10m
```

i hope you can help me :)
thank you

**Comment by matskiv** [comment]
Hello @stefanpinterBE 
Looks like a PV is not getting provisioned for the vcluster. It would be good to check the status of the PersistentVolumeClaim. 
Do you have a default StorageClass in your host cluster? If not, then you need to set a storage class via Helm values - `export HELM_VALUES="storage:\n  className: YOURSTORAGECLASS"`. I hope I formatted it correctly :laughing:

**Comment by matskiv** [comment]
Since there is no reply, I'll assume that the issue got resolved. We can reopen if more information about the root cause is provided.
