### ISSUE TITLE
HelmDeployFailed without explanation

### ISSUE THREAD

**Issue by wdonne** [loft-sh/cluster-api-provider-vcluster#30]
Hello,

In the attached live manifest and logs you can see that the Helm deployment failed. However, the output of Helm is not available, which makes it hard to find the root cause.

Best regards,

Werner.

[files.zip](https://github.com/loft-sh/cluster-api-provider-vcluster/files/11532039/files.zip)

**Comment by wdonne** [comment]
I found out in another way that the container image reference was wrong. However, after fixing it, it still wouldn't work with the provider, while using the same values file on the vcluster command-line worked fine.

**Comment by wdonne** [comment]
@FabianKramm Any thoughts?

**Comment by wdonne** [comment]
I have found the cause. After untarring the image `loftsh/cluster-api-provider-vcluster:0.1.3` I see this:

```
werner@saiph-30> file manager
manager: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=ZR0lKvvtW-D9L_y-YEXM/IxOJwjZkwX5Ttw6Vxwl3/V_U4DVqFq76NikCRHciG/yGHkXtVqdoO7_q5rYHpF, not stripped
werner@saiph-31> file helm
helm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=Sejujk9ETU7bH0Fn7XTi/4_74Imy8HTAgTrSY0GXG/JjrLt_my2OOf6Keucz3K/z1OSPDR7Z8xDiofSjJTY, stripped
```

The ARM variant of the image has an Intel version of the `helm` executable.

@FabianKramm I think this is a bug.

**Comment by heiko-braun** [comment]
Out if date
