### ISSUE TITLE
Deprecated? Please tell us! 👋

### ISSUE THREAD

**Issue by guettli** [loft-sh/cluster-api-provider-vcluster#42]
Afaik this project is deprecated.

Please add this important note at the top of the readme.

Thank you!

**Comment by kingdonb** [comment]
There are discussions that suggest the project is not deprecated, will be maintained again:

* loft-sh/vcluster#1345

**Comment by FabianKramm** [comment]
@guettli sorry for the delay on this, we will start actively maintaining this again, we will start by updating dependencies, adding more tests and then updating the supported vCluster versions as well.

**Comment by deniseschannon** [comment]
We have recently released `v0.2.0-alpha.1` and we're looking for feedback! Please open new issues if you test it out and let us know!
