### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by TylerGillson** [loft-sh/cluster-api-provider-vcluster#45]
I assume that since vcluster is [Apache 2.0 licensed](https://github.com/loft-sh/vcluster?tab=Apache-2.0-1-ov-file#readme), Loft would be ok with Apache 2.0 for cluster-api-provider-vcluster as well? Would be good to add a license to the repo!

**Comment by FabianKramm** [comment]
@TylerGillson we will update that soon, sorry for the delay

**Comment by TylerGillson** [comment]
@FabianKramm no worries - thanks for getting back to me! Raised a PR.

**Comment by LukasGentele** [comment]
LICENSE file added. Closing this
