### ISSUE TITLE
Allow vcluster creation in remote clusters

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/cluster-api-provider-vcluster#6]
Right now the provider is creating vclusters only in the management cluster of where cluster api is installed in. However, it would be nice if you could specify a kube config for a remote cluster where the provider should create the vcluster in. This would enable the cluster api provider to be installed into a pure management cluster while the actual vcluster could get managed somewhere else.

**Comment by casperprejler** [comment]
@FabianKramm 

I would be open to try and take this feature on. 

Is the main limitation of this because you cannot specify a kube config for a remote cluster?

**Comment by ThomasK33** [comment]
Hey @casperprejler,

Thanks for your initiative. The concept of remote vClusters introduces multiple complexities, including the kube config for a remote cluster you mentioned. Given the depth of these intricacies and potential security challenges, we're treating this feature with caution.

While we appreciate the community's enthusiasm, such a feature is more suited for specialized settings beyond the OSS version of vCluster. We want to suggest against creating a PR for this at this stage. 

Your insights and understanding as we shape vCluster's future are greatly appreciated.

**Comment by xinity** [comment]
@casperprejler perhaps using the pivot feature could be an alternative, what do you think ?
