### ISSUE TITLE
When new release of the CAPI provider?

### ISSUE THREAD

**Issue by mamu-reply** [loft-sh/cluster-api-provider-vcluster#60]
Hi guys! actually the VCluster helm is at the 0.19 version, and i've seen that inside main files there is 0.19.0 version as default, but the last release is at 0.1.3 with the max version support to 0.13.0 and default at 0.11.0, when will be released a new version with the newer helm support?
Thanks

# Goals

Release a new version of [https://github.com/loft-sh/cluster-api-provider-vcluster](https://github.com/loft-sh/cluster-api-provider-vcluster) that's compatible with 0.20 and provide some docs for it.

**Comment by mjnovice** [comment]
+1

**Comment by heiko-braun** [comment]
Hi @mamu-reply, there habe been a number of 0.19x releases, incorporating the latest enhancements and defects. That’s the version we‘d recommend to use.

Does this answer your question or did I misunderstand you?

**Comment by mamu-reply** [comment]
> Hi @mamu-reply, there habe been a number of 0.19x releases, incorporating the latest enhancements and defects. That’s the version we‘d recommend to use.
> 
> Does this answer your question or did I misunderstand you?

Hi @heiko-braun.
Yes, I want to use 0.19.x, but by default the latest release of this project (0.1.3) supports a maximum of 0.13.0.
I meant that I saw that some changes were made recently making the 0.19.0 version of the helmet the default, but it hasn't been re-released, so it's still unusable.

**Comment by heiko-braun** [comment]
@mamu-reply my bad, I didn't realize we talk about the CAPI provider.

Long story short: CAPI provider is work in progress and recently got more attention. I don't have any concrete dates yet, but you can expect an new release soon. However, that currently hinges on 0.20.x (current vcluster main) to become more stable.

**Comment by mamu-reply** [comment]
> @mamu-reply my bad, I didn't realize we talk about the CAPI provider.
> 
> Long story short: CAPI provider is work in progress and recently got more attention. I don't have any concrete dates yet, but you can expect an new release soon. However, that currently hinges on 0.20.x (current vcluster main) to become more stable.

Oh, I understand, Thanks.
For now as workaround I'm using the latest release by installing 0.13.0 helm version and then i will do a manual helm upgrade to 0.19.3 version, it work, but is not a very intuitive method.

**Comment by whiskeyjimbo** [comment]
@mamu-reply i'm currently trying to test this for a future project, can you give any specifics on what you did to make it work while we wait for updates?

**Comment by mjnovice** [comment]
@mamu-reply manual helm upgrade of the vcluster your mean ?

**Comment by mamu-reply** [comment]
> @mamu-reply manual helm upgrade of the vcluster your mean ?

Yes

**Comment by heiko-braun** [comment]
There is an updated pre-release available. Maybe you want to give it a try? https://github.com/loft-sh/cluster-api-provider-vcluster/releases/tag/v0.2.0-alpha.1
